### PR TITLE
Make the tmux command global

### PR DESCRIPTION
**Pull request by vesln**
Sort of convenient access to the created by nexus tmux session.

### CODE REVIEW

**Comment by skanev** [comment]
How are you using it?

**Comment by vesln** [comment]
85d9b0a

**Comment by skanev** [comment]
Wouldn't it be more convenient to have a command for that, like:

```
:NexusSend ls
```

**Comment by vesln** [comment]
Probably. The current implementation gives you the ability to switch more easily from vimux, since you only have to change the function name. Having `:NesuxSend` would be great, but both can live together.

**Pull request closed without merging**
